### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by scotto**
change polyfuse from 1206 to 1812

### CODE REVIEW

**Comment by linker3000** [comment]
Thanks for spotting that.

**Comment by scotto** [comment]
You're welcome -- and thanks for making this! I noticed because I was
ordering parts and couldn't find the original, that's all.

On Mon, Feb 24, 2020 at 01:25:32PM -0800, Nigel Kendrick wrote:
> Thanks for spotting that.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/linker3000/shukran/pull/2#issuecomment-590556350

-- 
J. Scott Hepler (he/him)
sysadmin and full-stack web dev
802.281.4392
http://scotthepler.com

**Comment by linker3000** [comment]
Before you spot it too, the prototypes in the photos have some slightly different parts from the BOM  - mainly the LED resistors (I seem to be awash with 390R and not so many 330s!).

**Comment by scotto** [comment]
OK, thanks for the heads-up! I'm on a fairly-steep learning curve here, so
would have gotten there sooner-or-later. Thanks again!

On Mon, Feb 24, 2020 at 01:48:46PM -0800, Nigel Kendrick wrote:
> Before you spot it too, the prototypes in the photos have some slightly different parts from the BOM  - mainly the LED resistors (I seem to be awash with 390R and not so many 330s!).
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/linker3000/shukran/pull/2#issuecomment-590565804

-- 
J. Scott Hepler (he/him)
sysadmin and full-stack web dev
802.281.4392
http://scotthepler.com

**Pull request merged**
